version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpassword
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    networks:
      - nestnetwork

networks:
  nestnetwork:
    driver: bridge
