version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - nestnetwork

networks:
  nestnetwork:
    driver: bridge
